### ISSUE TITLE
怎么在luci的web界面里加上虚拟wan

### ISSUE THREAD

**Issue by fsaimon** [981213/openwrt#10]
小白经历千辛万苦编译出跟你在恩山放的相似的功能的固件后发现luci的web界面里没有虚拟wan的创建条目。。。求指导

**Comment by fsaimon** [comment]
我选了multilink这个包 可是wed里没有条目。。。

**Comment by 981213** [comment]
2 那玩意儿是luci-app-syncdial，不是官方软件包，在我luci里面。但是openwrt源码也需要许多改动才能使用。
1 我放在这里的源码现在因为trunk坑爹所以编译出来的固件也是不太正常的……这里的源码近期先别用……

**Comment by fsaimon** [comment]
ok 谢谢
