### ISSUE TITLE
你好，想问一下newifi Y1的usb GPIO

### ISSUE THREAD

**Issue by yuqianma** [981213/openwrt#15]
看到你提供了Y1S 3个USB设置，想问一下你知道newifi mini 的USB是怎么供电的吗？
能不能通过GPIO控制USB开关？

以前TP的一个路由刷了openwrt 通过控制GPIO8 value就可以开关。但是这个一是找不到具体USB GPIO，二是，随意export几个设置value，什么都没发生。对嵌入式编程不太熟悉，请问你有没有什么思路，谢谢。

**Comment by 981213** [comment]
Y1没有这类电路设计，不需要通过系统来控制USB电源。

**Comment by yuqianma** [comment]
Thanks.
