### ISSUE TITLE
编译Ngrok时报错

### ISSUE THREAD

**Issue by soulmercy** [981213/openwrt#20]
make[4]: Entering directory `/home/jeff/openwrt/981213/build_dir/target-mips_34kc_musl-1.1.14/ngrokc-2b2d4ae'
mips-openwrt-linux-musl-g++ -fexceptions -DOPENSSL=1 -O2   -c -o sendmsg.o sendmsg.cpp
mips-openwrt-linux-musl-gcc -Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -g3 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -iremap /home/jeff/openwrt/981213/build_dir/target-mips_34kc_musl-1.1.14/ngrokc-2b2d4ae:ngrokc-2b2d4ae -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/home/jeff/openwrt/981213/staging_dir/target-mips_34kc_musl-1.1.14/usr/include -I/home/jeff/openwrt/981213/staging_dir/target-mips_34kc_musl-1.1.14/include -I/home/jeff/openwrt/981213/staging_dir/toolchain-mips_34kc_gcc-5.3.0_musl-1.1.14/usr/include -I/home/jeff/openwrt/981213/staging_dir/toolchain-mips_34kc_gcc-5.3.0_musl-1.1.14/include/fortify -I/home/jeff/openwrt/981213/staging_dir/toolchain-mips_34kc_gcc-5.3.0_musl-1.1.14/include  -fexceptions -DOPENSSL=1 -O2   -c -o cJSON.o cJSON.c
mips-openwrt-linux-musl-g++ -fexceptions -DOPENSSL=1 -O2   -c -o nonblocking.o nonblocking.cpp
mips-openwrt-linux-musl-g++ -fexceptions -DOPENSSL=1 -O2   -c -o sslbio.o sslbio.cpp
mips-openwrt-linux-musl-g++ -fexceptions -DOPENSSL=1 -O2   -c -o ngrok.o ngrok.cpp
mips-openwrt-linux-musl-g++ -fexceptions -DOPENSSL=1 -O2   -c -o main.o main.cpp
mips-openwrt-linux-musl-g++ -s sendmsg.o cJSON.o nonblocking.o sslbio.o ngrok.o main.o -o ngrokc -lpthread -lssl -lcrypto
sendmsg.o: In function `SendReqTunnel(int, ssl_st*, char const*, char const*, char const*, int, char*)':
sendmsg.cpp:(.text+0x300): undefined reference to `SslWrite'
sendmsg.cpp:(.text+0x304): undefined reference to `SslWrite'
main.o: In function `proxy()':
main.cpp:(.text+0x290): undefined reference to `SslWrite'
main.cpp:(.text+0x9ac): undefined reference to `SslWrite'
main.o: In function `main':
main.cpp:(.text.startup+0x180): undefined reference to `AbreSSL()'
nonblocking.o: In function `clearsock(int, sockinfo*)':
nonblocking.cpp:(.text+0x98): undefined reference to `SslShutdown'
nonblocking.cpp:(.text+0x9c): undefined reference to `SslShutdown'
nonblocking.cpp:(.text+0xac): undefined reference to `SslFree'
nonblocking.cpp:(.text+0xb0): undefined reference to `SslFree'
nonblocking.cpp:(.text+0xc0): undefined reference to `SslCtxFree'
nonblocking.cpp:(.text+0xc4): undefined reference to `SslCtxFree'
sslbio.o: In function `openssl_init_info(int, openssl_info*)':
sslbio.cpp:(.text+0x0): undefined reference to `SslMethodV23'
sslbio.cpp:(.text+0x8): undefined reference to `SslMethodV23'
sslbio.cpp:(.text+0xc): undefined reference to `SslCtxNew'
sslbio.cpp:(.text+0x28): undefined reference to `SslCtxNew'
sslbio.cpp:(.text+0x48): undefined reference to `SslNew'
sslbio.cpp:(.text+0x4c): undefined reference to `SslNew'
sslbio.cpp:(.text+0x5c): undefined reference to `SslSetFd'
sslbio.cpp:(.text+0x60): undefined reference to `SslSetFd'
sslbio.cpp:(.text+0x74): undefined reference to `SslSetConnectState'
sslbio.cpp:(.text+0x78): undefined reference to `SslSetConnectState'
sslbio.cpp:(.text+0x80): undefined reference to `SslDoHandshake'
sslbio.cpp:(.text+0x9c): undefined reference to `SslDoHandshake'
sslbio.cpp:(.text+0x88): undefined reference to `SslGetError'
sslbio.cpp:(.text+0xb8): undefined reference to `SslGetError'
sslbio.cpp:(.text+0x120): undefined reference to `SslDoHandshake'
ngrok.o: In function `ConnectMain(int, int*, sockaddr_in, openssl_info**, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::map<int, sockinfo*, std::less<int>, std::allocator<std::pair<int const, sockinfo*> > >*, char*)':
ngrok.cpp:(.text+0x570): undefined reference to `SslWrite'
ngrok.cpp:(.text+0x574): undefined reference to `SslWrite'
ngrok.o: In function `RemoteSslInit(std::_Rb_tree_iterator<std::pair<int const, sockinfo*> >*, sockinfo*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::map<int, sockinfo*, std::less<int>, std::allocator<std::pair<int const, sockinfo*> > >*)':
ngrok.cpp:(.text+0x838): undefined reference to `SslWrite'
ngrok.cpp:(.text+0x83c): undefined reference to `SslWrite'
ngrok.o: In function `LocalToRemote(std::_Rb_tree_iterator<std::pair<int const, sockinfo*> >*, char*, int, sockinfo*, openssl_info*, std::map<int, sockinfo*, std::less<int>, std::allocator<std::pair<int const, sockinfo*> > >*)':
ngrok.cpp:(.text+0x944): undefined reference to `SslWrite'
ngrok.o:ngrok.cpp:(.text+0x948): more undefined references to `SslWrite' follow
ngrok.o: In function `RemoteToLocal(openssl_info*, int, char*, sockinfo*, std::_Rb_tree_iterator<std::pair<int const, sockinfo*> >*, std::map<int, sockinfo*, std::less<int>, std::allocator<std::pair<int const, sockinfo*> > >*)':
ngrok.cpp:(.text+0x9d8): undefined reference to `SslRead'
ngrok.cpp:(.text+0x9e8): undefined reference to `SslRead'
ngrok.cpp:(.text+0xa14): undefined reference to `SslGetError'
ngrok.cpp:(.text+0xa18): undefined reference to `SslGetError'
ngrok.o: In function `CmdSock(int*, int, char*, sockinfo*, std::map<int, sockinfo*, std::less<int>, std::allocator<std::pair<int const, sockinfo*> > >*, char*, sockaddr_in, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, char*, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > >*, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, TunnelInfo*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, TunnelInfo*> > >*)':
ngrok.cpp:(.text+0x13d0): undefined reference to `SslRead'
ngrok.cpp:(.text+0x13e0): undefined reference to `SslRead'
ngrok.cpp:(.text+0x13f8): undefined reference to `SslGetError'
ngrok.cpp:(.text+0x13fc): undefined reference to `SslGetError'
ngrok.cpp:(.text+0x1810): undefined reference to `SslWrite'
ngrok.cpp:(.text+0x1814): undefined reference to `SslWrite'
ngrok.cpp:(.text+0x19a0): undefined reference to `SslWrite'
ngrok.cpp:(.text+0x19a4): undefined reference to `SslWrite'
ngrok.o: In function `ConnectLocal(openssl_info*, char*, int, std::_Rb_tree_iterator<std::pair<int const, sockinfo*> >*, sockinfo*, std::map<int, sockinfo*, std::less<int>, std::allocator<std::pair<int const, sockinfo*> > >*, char*, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, TunnelInfo*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, TunnelInfo*> > >*, TunnelInfo*)':
ngrok.cpp:(.text+0x1a20): undefined reference to `SslRead'
ngrok.cpp:(.text+0x1a2c): undefined reference to `SslRead'
ngrok.cpp:(.text+0x1a84): undefined reference to `SslGetError'
ngrok.cpp:(.text+0x1a88): undefined reference to `SslGetError'
collect2: error: ld returned 1 exit status
make[4]: *** [ngrokc] Error 1
make[4]: Leaving directory `/home/jeff/openwrt/981213/build_dir/target-mips_34kc_musl-1.1.14/ngrokc-2b2d4ae'
make[3]: *** [/home/jeff/openwrt/981213/build_dir/target-mips_34kc_musl-1.1.14/ngrokc-2b2d4ae/.built] Error 2
make[3]: Leaving directory `/home/jeff/openwrt/981213/package/my_package/ngrok-c'
make[2]: *** [package/my_package/ngrok-c/compile] Error 2
make[2]: Leaving directory `/home/jeff/openwrt/981213'
make[1]: *** [/home/jeff/openwrt/981213/staging_dir/target-mips_34kc_musl-1.1.14/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/jeff/openwrt/981213'
make: *** [world] 错误 2

**Comment by soulmercy** [comment]
用的wndr3700v4，一直眼红你最新版里dnsmasq里的那个chinadns，所以想自己变一下。自己选了些参数，编译到这里报错了。看上去都是SSL的，是选择的library有问题么？

**Comment by auslin45** [comment]
makefile里少编译了一个文件，参考openwrtbuildv2.sh就知道少了openssldl.o，makefile改成
CC?=gcc
CXX?=g++
CFLAGS+=-fexceptions -DOPENSSL=1 -O2
CXXFLAGS=-fexceptions -DOPENSSL=1 -O2
LIBS=sendmsg.o openssldl.o cJSON.o nonblocking.o sslbio.o ngrok.o main.o
all:: ngrokc $(LIBS)
ngrokc: $(LIBS)
	$(CXX) -s $(LIBS) -o ngrokc -lpthread -lssl -lcrypto
sendmsg.o: sendmsg.h
openssldl.o: openssldl.h
cJSON.o: cJSON.h
nonblocking.o: nonblocking.h
sslbio.o: sslbio.h
ngrok.o: ngrok.h
main.o: sendmsg.h openssldl.h sslbio.h ngrok.h cJSON.h bytestool.h nonblocking.h

clean:
	rm -f $(LIBS) ngrokc
编译通过，请蝈蝈大神修正一下

**Comment by 981213** [comment]
麻烦去ngrok-c项目提交issue或者pull request行么。。。传送门： https://github.com/dosgo/ngrok-c
工作日期间在学校，电脑没环境进行这些操作。

**Comment by auslin45** [comment]
已经在dosgo大神那里pull request了，不过你这边的Makefile还是要改一下啊，要不然git clone的不是最新版的ngrok-c

**Comment by 981213** [comment]
你漏加-ldl了
我等他合并我的pull request后再改。。。

**Comment by auslin45** [comment]
嗨，大神，我又更新了一下ngrokc的Makefile.openssl，跟随主线更新，去掉openssl里编译的-lpthread参数，新版不使用pthread线程了。。编译后使用没什么异常，每个进程内存占用3%，已经合并进dosgo大神的代码库里了
