### ISSUE TITLE
石像鬼QoS编译出错

### ISSUE THREAD

**Issue by 981213** [981213/openwrt#4]
iproute2更新至4.0.0 部分函数无法使用

**Comment by wongsyrone** [comment]
已经上报到官方http://www.gargoylerouter.com/gargoyle/issues/98
另外从这里http://fossies.org/diffs/iproute2/3.19.0_vs_4.0.0/可以看iproute2两个版本的区别

**Comment by wongsyrone** [comment]
尝试性弄了两个方案：
方案一： https://github.com/wongsyrone/openwrt-1/commit/7f86ba1b3706f82e3fa33b19111400a864463aff  其中提交说明有说为什么这样做。
后来又研究了一下，感觉还是不是特别合适，于是
方案二：https://github.com/wongsyrone/openwrt-1/commit/e944e25c18dc839b2bf3e8a90f1b25b4c67abe2e  这是我目前比较倾向的解决方法。
蝈蝈大神有什么研究吗？

**Comment by kuoruan** [comment]
石像鬼编译确实有问题，找到了解决方法，看这里：
https://github.com/ericpaulbishop/gargoyle/issues/355

**Comment by kuoruan** [comment]
还需要一个patch:
```diff
--- a/qosmon.c
+++ b/qosmon.c
@@ -34,6 +34,8 @@
 #include <string.h>
 #include <errno.h>
 #include <time.h>
+#include <limits.h>
+#include <sys/param.h>
 
 #include "utils.h"
 #include "tc_util.h"
```

**Comment by 981213** [comment]
难得有大神前来修复石像鬼在musl下的编译啊……膜拜……

**Comment by wongsyrone** [comment]
qosmon的并不需要

**Comment by kuoruan** [comment]
然而还是编译不过，我放弃了

**Comment by wongsyrone** [comment]
有兴趣的看这条commit https://github.com/wongsyrone/openwrt-1/commit/a02641affadc21a32f8b7fb56bcb6f243935efc1

**Comment by wongsyrone** [comment]
如果用了我上面的那条commit的修改，需要重新编译工具链，因为加了个musl的patch

**Comment by zhuanshicong** [comment]
直接把@fjkfwz错误提示里面的11个 (__sighandler_t)删掉就可以继续编译 不知道最后会有什么问题..

**Comment by 981213** [comment]
石像鬼已删除。。。这个坑不管了。。
qosmon musl不能编译的问题。。有空再看
